services:
  strapi:
    image: strapi/strapi
    container_name: strapi
    environment:
      DATABASE_CLIENT: 'sqlite'
      DATABASE_FILENAME: './.tmp/data.db'
    volumes:
      - ./strapi:/srv/app
    ports:
      - '1337:1337'
    networks:
      - chemotion-strapi
    restart: unless-stopped

networks:
  chemotion-strapi:
    name: chemotion-strapi
